# Generated by Django 6.0.5 on 2026-05-18 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('phone', models.TextField()),
                ('product_name', models.CharField(max_length=100)),
                ('nin', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255, unique=True)),
                ('product_description', models.CharField(max_length=255)),
                ('amount_paid', models.IntegerField()),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('balance_remaining', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('buying_price', models.IntegerField()),
                ('current_stock', models.IntegerField(default=0)),
                ('threshold', models.IntegerField(default=10)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashier', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('distance', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField()),
                ('transport_fee', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('payment', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16)),
                ('employee_id', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'admin'), ('sales_attendant', 'sales_attendant'), ('store_manager', 'store_manager')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('TRN', models.TextField()),
                ('phone', models.TextField()),
                ('product_description', models.TextField()),
                ('payment_option', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', models.DateField()),
                ('deposit_amount', models.IntegerField()),
                ('expected_completion', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Finished', 'Finished')], max_length=20)),
                ('Customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondoapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('units', models.CharField(max_length=20)),
                ('cost_price', models.IntegerField()),
                ('selling_price', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('buyer_type', models.CharField(max_length=50)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='nyondoapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Scredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount_owed', models.IntegerField()),
                ('status', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondoapp.supplier')),
            ],
        ),
    ]
